extends: conditional
message: "Spell out '%s', if it's unfamiliar to the audience."
link: 'https://developers.google.com/style/abbreviations'
level: suggestion
ignorecase: false
# Ensures that the existence of 'first' implies the existence of 'second'.
first: '\b([A-Z]{3,5})\b'
second: '(?:\b[A-Z][a-z]+ )+\(([A-Z]{3,5})\)'
# ... with the exception of these:
exceptions:
  - Ox
  - 24/7
  - 401(k)
  - 50/50
  - API
  - ASP
  - ASCII
  - BPF
  - BGP
  - CEX
  - CLI
  - CPU
  - CSS
  - CSV
  - CVE
  - dApp
  - DAO
  - DDoS
  - DEBUG
  - DeFi
  - DEX
  - DNS
  - DOM
  - DPI
  - EVM
  - ERC
  - ERC-20
  - ERC20ForSpl
  - ERC20ForSplMintable
  - ERC-721
  - FAQ
  - GCC
  - GDB
  - GET
  - GHz
  - GPU
  - GTK
  - GUI
  - HAMT
  - HTML
  - HTTP
  - HTTPS
  - IDE
  - INI
  - I/O
  - JAR
  - JSON
  - JSX
  - L1
  - L2
  - LDAP
  - LESS
  - LLDB
  - Mbps
  - NET
  - NFT
  - NEON
  - N-tx
  - N-txs
  - NodeJS
  - NOTE
  - NVDA
  - OSS
  - PATH
  - PDF
  - PHP
  - P2P
  - PoH
  - PoS
  - POST
  - PoW
  - POST
  - RAM
  - REPL
  - REST
  - R&D
  - RPC
  - RSA
  - SCM
  - SCSS
  - SDK
  - SMTP
  - SQL
  - SOL
  - SPL
  - SSH
  - SSL
  - SVG
  - TBD
  - TCP
  - TODO
  - TL;DR
  - TPS
  - tx
  - URI
  - URL
  - US
  - USA
  - USB
  - UTF
  - VM
  - VPS
  - XML
  - XSS
  - YAML
  - ZIP
