extends: capitalization
message: "'%s' should use sentence-style capitalization."
link: 'https://developers.google.com/style/capitalization#capitalization-in-titles-and-headings'
level: warning
scope: heading
match: $sentence
indicators:
  - ':'
exceptions:
  - Azure
  - CLI
  - Code
  - Cosmos
  - Docker
  - Emmet
  - gRPC
  - I
  - Kubernetes
  - Linux
  - macOS
  - Marketplace
  - MetaMask
  - MongoDB
  - Neon EVM
  - NEON
  - Neon
  - Neon Foundation
  - Neon Labs
  - NeonSwap
  - NeonScan
  - NeonPass
  - NeonFaucet
  - NeonAnalytics
  - Neon Web3 Proxy
  - REPL
  - Studio
  - TypeScript
  - URLs
  - Vale
  - Visual
  - VS
  - Windows
