extends: existence
message: "Avoid using '%s'. Stick to the present tense."
link: 'https://developers.google.com/style/tense'
ignorecase: true
level: warning
tokens:
  - will
  - won't
  - \'ll
  - shall
